SELECT DOSS.ANCREFDOSS CONTRATO,
    --DE.DF_MON_DOS  IMPORTE_FACTURA,  -- MONTO TOTAL DE LA FACTURA SIN IVA
    DE.DF_MONTTC_DOS  IMPORTE_FACTURA,  -- MONTO TOTAL DE LA FACTURA CON IVA
    NVL((SELECT SUM(V2.MONTANT) MONTOPAGO FROM IMXDB.G_VENELEM V2 WHERE V2.REFELEM=EL.REFELEM),0.00) IMPORTE_PAGADO,  -----  IMPORTE CON IVA
    NVL((SELECT MAX(TRUNC(V2.DTJOUR_DT)) MONTOPAGO FROM IMXDB.G_VENELEM V2 WHERE V2.REFELEM=EL.REFELEM),TRUNC(SYSDATE)) - TRUNC(FE.ER_DAT_DT)  DIAS_ATRASO,   --- SE CONSIDERA POR LA FECHA DE EMISION DE LA FACTURA
    (SELECT VALEUR_ES FROM IMXDB.V_DOMAINE where ABREV = DE.DF_NOM AND TYPE = 'FACTURE')||' '||NVL(NVL(TA.INSTAL_NUMBER, TA_H.INSTAL_NUMBER),0)||'/'||NVL(NVL(UTAV.MAX_INSTAL_NUMBER, UTAV_H.MAX_INSTAL_NUMBER),0) CONCEPTO,
    TRIM(to_char(FE.ER_REG_DT, 'Month','nls_date_language=spanish'))||'-'||to_char(FE.ER_REG_DT,'YYYY') PERIODO,
    FE.ER_REFEXT1 FOLIO,  --SOLO PARA VALIDACIONES
    FE.ER_DAT_DT  Fecha_emision_factura,  --SOLO PARA VALIDACIONES
    FE.ER_REG_DT  Fecha_Vencimiento_factura, -- SOLO PARA VALIDACIONES
    (SELECT MAX(V2.DTJOUR_DT)  FROM IMXDB.G_VENELEM V2 WHERE V2.REFELEM=EL.REFELEM) FECHA_APL_PAGO    ---Fecha emisión factura,
FROM IMXDB.F_ENTREL FE 
    INNER JOIN IMXDB.F_DETFAC DE ON FE.ER_NUM = DE.DF_REL
    INNER JOIN IMXDB.G_ELEMFI EL ON (EL.LIBELLE_20_2 = DE.DF_NUM AND  EL.REFDOSS = DE.DF_DOS)
    INNER JOIN IMXDB.G_DOSSIER DOSS ON EL.REFDOSS = DOSS.REFDOSS
    
    LEFT JOIN (SELECT TFA.REFDOSS_REQST, TFA.IMX_UN_ID, TFA.FLAG_ACTIVE, TAI.REFELEM_FI_INT,
            TAI.FIN_AMORT_ID, TAI.INTEREST_INSTALLMENT, TAI.CAPITAL_INSTALLMENT, TAI.INSTAL_DUE_DT, TAI.REFELEM_FI_INST, TAI.REFELEM_FI_INST_ADM, TAI.REFELEM_FI_INST_LEAS, TAI.FG_IS_INVOICED, 'I' TABLA_ORIG,TAI.REFELEM_FI_CAP, TAI.INSTAL_NUMBER
        FROM IMXDB.T_FIN_AMO TFA
            INNER JOIN IMXDB.T_AMORT_INSTAL TAI ON TFA.IMX_UN_ID = TAI.FIN_AMORT_ID
        WHERE TFA.FLAG_ACTIVE = 'O') TA ON (DE.DF_DOS = TA.REFDOSS_REQST AND TA.REFELEM_FI_INST = EL.REFELEM )  ---- TABLA DE AMORTIZACION ACTIVA
        
    LEFT JOIN (SELECT TFA.REFDOSS_REQST, TFA.IMX_UN_ID, TFA.FLAG_ACTIVE,
            TAI.FIN_AMORT_ID, TAI.INTEREST_INSTALLMENT, TAI.CAPITAL_INSTALLMENT, TAI.INSTAL_DUE_DT, TAI.REFELEM_FI_INST, TAI.REFELEM_FI_INST_ADM, TAI.REFELEM_FI_INST_LEAS, TAI.FG_IS_INVOICED, TAI.REFELEM_FI_CAP, TAI.REFELEM_FI_INT, TAI.INSTAL_NUMBER
        FROM IMXDB.T_FIN_AMO TFA --ON (UNIV_FACT.DF_DOS = TFA.REFDOSS_REQST)
            INNER JOIN IMXDB.T_AMORT_HISTO TAI ON TFA.IMX_UN_ID = TAI.FIN_AMORT_ID) TA_H ON (DE.DF_DOS = TA_H.REFDOSS_REQST AND TA_H.REFELEM_FI_INST = EL.REFELEM)   ---- TABLA DE AMORTIZACION HISTÓRICA
            
    LEFT JOIN (SELECT FIN_AMORT_ID,max(TAI.INSTAL_NUMBER) MAX_INSTAL_NUMBER
        FROM IMXDB.T_AMORT_INSTAL TAI
        GROUP BY FIN_AMORT_ID) UTAV
    ON (TA.IMX_UN_ID = UTAV.FIN_AMORT_ID)
    
    LEFT JOIN (SELECT FIN_AMORT_ID,max(TAI.INSTAL_NUMBER) MAX_INSTAL_NUMBER
        FROM IMXDB.T_AMORT_HISTO TAI
        GROUP BY FIN_AMORT_ID)UTAV_H
    ON (TA_H.IMX_UN_ID = UTAV_H.FIN_AMORT_ID)
    
    LEFT JOIN (SELECT DDD.ER_REFEXT1 AS FOLIO_FACT, DDD.FEC_CANCELACION AS FECHA_CANC
        FROM (SELECT DISTINCT CCC.ER_REFEXT1, CCC.FEC_CANCELACION, RANK() OVER (PARTITION BY  CCC.ER_REFEXT1  ORDER BY CCC.FEC_CANCELACION ) NUM_CANCELACION
            FROM (SELECT DISTINCT F.ER_REFEXT1, max(DET.DF_ANN_DT) FEC_CANCELACION
                FROM imxdb.F_ENTREL f, imxdb.F_ENTREL e, imxdb.f_detfac det
                WHERE F.er_num = e.ER_ORG_INVOICE_REF and det.df_rel = e.er_num and e.ER_ORG_INVOICE_REF IS NOT NULL and E.ER_TCR > 0
                GROUP BY F.ER_REFEXT1
                UNION ALL
                SELECT DISTINCT ER.ER_REFEXT1 , MIN (DF.DF_ANN_DT) FEC_CANCELACION
                FROM IMXDB.F_ENTREL ER INNER JOIN IMXDB.F_DETFAC DF ON (ER.ER_NUM = DF.DF_REL)
                WHERE DF.DF_ANN IS NOT NULL AND DF.DF_SEN = 'D' AND DF.DF_ANN_DT > '31/12/2019' AND ER.ER_REFEXT1 IS NOT NULL
                GROUP BY ER.ER_REFEXT1
            ) CCC
        ) DDD
        WHERE DDD.NUM_CANCELACION = 1
            AND FEC_CANCELACION < TRUNC(sysdate,'DD')    ) CANC ON CANC.FOLIO_FACT = FE.ER_REFEXT1
            
WHERE FE.ER_NUM NOT IN ( SELECT FE.ER_NUM
    FROM IMXDB.F_ENTREL FE, imxdb.F_ENTREL E
    WHERE FE.ER_NUM = E.ER_ORG_INVOICE_REF
    AND E.ER_ORG_INVOICE_REF IS NOT NULL AND E.ER_TCR > 0 ) --- QUITAR CANCELADAS
    
AND CANC.FECHA_CANC IS NULL
AND FE.ER_REFEXT1 IS NOT NULL
AND DE.DF_INV_GROUP = 'A'                         ----- PARA TRAER SÓLO FACTURAS DE RENTAS
AND DE.DF_NOM IN ('LOY','FRAD','FRLO')            ----- PARA TRAER SÓLO FACTURAS DE RENTAS

AND DOSS.ANCREFDOSS = '