//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCLeasing.CRUD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientesABC
    {
        public decimal user_id { get; set; }
        public string token { get; set; }
        public string device_type { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public System.DateTime created_at { get; set; }
        public string no_cliente { get; set; }
        public string RFC { get; set; }
        public string password { get; set; }
        public string nombre { get; set; }
    }
}
